# Generated by Django 5.2.4 on 2025-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.AddField(
            model_name='certificate',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='core.skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_preview_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
