# Generated by Django 5.2.4 on 2025-07-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certificate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verify_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
